-- Create table: departments
CREATE TABLE departments (
  dept_id STRING(36) NOT NULL,
  dept_name STRING(50) NOT NULL,
  location STRING(100),
  created_at TIMESTAMP DEFAULT (CURRENT_TIMESTAMP())
) PRIMARY KEY (dept_id);

-- Create table: employees
CREATE TABLE employees (
  emp_id STRING(36) NOT NULL,
  first_name STRING(50) NOT NULL,
  last_name STRING(50) NOT NULL,
  email STRING(150),
  hire_date DATE NOT NULL,
  salary NUMERIC,
  dept_id STRING(36),
  manager_id STRING(36),
  phone_number STRING(20)
) PRIMARY KEY (emp_id);

-- Add foreign keys separately to avoid dependency errors
ALTER TABLE employees ADD CONSTRAINT FK_employees_dept FOREIGN KEY (dept_id) REFERENCES departments (dept_id);
ALTER TABLE employees ADD CONSTRAINT FK_employees_mgr FOREIGN KEY (manager_id) REFERENCES employees (emp_id);

-- Create index on employee email
CREATE UNIQUE INDEX idx_emp_email ON employees(email);

-- Create table: projects
CREATE TABLE projects (
  project_id STRING(36) NOT NULL,
  project_name STRING(100) NOT NULL,
  start_date DATE,
  end_date DATE,
  budget NUMERIC,
  status STRING(20) DEFAULT ("ACTIVE")
) PRIMARY KEY (project_id);

-- Add check constraints for projects
ALTER TABLE projects ADD CONSTRAINT check_dates CHECK (end_date > start_date);
ALTER TABLE projects ADD CONSTRAINT check_status CHECK (status IN ("ACTIVE", "COMPLETED", "ON_HOLD", "CANCELLED"));

-- Create table: project_assignments
CREATE TABLE project_assignments (
  emp_id STRING(36) NOT NULL,
  project_id STRING(36) NOT NULL,
  role STRING(50),
  hours_allocated INT64,
) PRIMARY KEY (emp_id, project_id);

-- Add foreign key constraints for project_assignments
ALTER TABLE project_assignments ADD CONSTRAINT FK_pa_emp FOREIGN KEY (emp_id) REFERENCES employees (emp_id);
ALTER TABLE project_assignments ADD CONSTRAINT FK_pa_project FOREIGN KEY (project_id) REFERENCES projects (project_id);

-- Create additional indexes
CREATE INDEX idx_emp_name ON employees(last_name, first_name);
CREATE INDEX idx_dept_location ON departments(location);
CREATE INDEX idx_project_status ON projects(status);

-- Create view: employee_details
CREATE VIEW employee_details SQL SECURITY INVOKER AS
SELECT 
  e.emp_id,
  e.first_name,
  e.last_name,
  e.email,
  d.dept_name,
  m.first_name AS manager_first_name,
  m.last_name AS manager_last_name
FROM employees e
LEFT JOIN departments d ON e.dept_id = d.dept_id
LEFT JOIN employees m ON e.manager_id = m.emp_id;

-- Example inserts: UUIDs must be generated by client and passed in
-- Insert into departments
INSERT INTO departments (dept_id, dept_name, location)
VALUES ("generated-uuid-1", "Engineering", "New York");

-- Insert into employees
INSERT INTO employees (emp_id, first_name, last_name, email, hire_date, salary, dept_id)
VALUES ("generated-uuid-2", "Alice", "Smith", "alice@example.com", DATE "2023-01-01", 90000.00, "generated-uuid-1");

-- Insert into projects
INSERT INTO projects (project_id, project_name, start_date, end_date, budget, status)
VALUES ("generated-uuid-3", "Project Apollo", DATE "2023-03-01", DATE "2023-09-01", 500000.00, "ACTIVE");

-- Insert into project_assignments
INSERT INTO project_assignments (emp_id, project_id, role, hours_allocated)
VALUES ("generated-uuid-2", "generated-uuid-3", "Developer", 120);

-- Query with joins
SELECT 
  e.emp_id, 
  e.first_name, 
  e.last_name, 
  e.email, 
  d.dept_name, 
  m.first_name AS manager_first_name, 
  m.last_name AS manager_last_name,
  p.project_name
FROM employees e
LEFT JOIN departments d ON e.dept_id = d.dept_id
LEFT JOIN employees m ON e.manager_id = m.emp_id
LEFT JOIN project_assignments pa ON e.emp_id = pa.emp_id
LEFT JOIN projects p ON pa.project_id = p.project_id;

-- Drop view
DROP VIEW employee_details;

-- Drop indexes
DROP INDEX idx_project_status;
DROP INDEX idx_dept_location;
DROP INDEX idx_emp_name;
DROP INDEX idx_emp_email;

-- Drop tables
DROP TABLE project_assignments;
DROP TABLE projects;
DROP TABLE employees;
DROP TABLE departments;