CREATE TABLE Third_Party_Companies (
  company_id INT64 NOT NULL GENERATED BY DEFAULT AS IDENTITY (START WITH 1 INCREMENT BY 1),
  company_type STRING(5) NOT NULL,
  company_name STRING(255),
  company_address STRING(255),
  other_company_details STRING(255)
) PRIMARY KEY (company_id);

CREATE TABLE Maintenance_Contracts (
  maintenance_contract_id INT64 NOT NULL GENERATED BY DEFAULT AS IDENTITY (START WITH 1 INCREMENT BY 1),
  maintenance_contract_company_id INT64 NOT NULL,
  contract_start_date TIMESTAMP,
  contract_end_date TIMESTAMP,
  other_contract_details STRING(255),
  FOREIGN KEY (maintenance_contract_company_id) REFERENCES Third_Party_Companies(company_id)
) PRIMARY KEY (maintenance_contract_id);

CREATE TABLE Parts (
  part_id INT64 NOT NULL GENERATED BY DEFAULT AS IDENTITY (START WITH 1 INCREMENT BY 1),
  part_name STRING(255),
  chargeable_yn STRING(1),
  chargeable_amount NUMERIC,
  other_part_details STRING(255)
) PRIMARY KEY (part_id);

CREATE TABLE Skills (
  skill_id INT64 NOT NULL GENERATED BY DEFAULT AS IDENTITY (START WITH 1 INCREMENT BY 1),
  skill_code STRING(20),
  skill_description STRING(255)
) PRIMARY KEY (skill_id);

CREATE TABLE Staff (
  staff_id INT64 NOT NULL GENERATED BY DEFAULT AS IDENTITY (START WITH 1 INCREMENT BY 1),
  staff_name STRING(255),
  gender STRING(1),
  other_staff_details STRING(255)
) PRIMARY KEY (staff_id);

CREATE TABLE Assets (
  asset_id INT64 NOT NULL GENERATED BY DEFAULT AS IDENTITY (START WITH 1 INCREMENT BY 1),
  maintenance_contract_id INT64 NOT NULL,
  supplier_company_id INT64 NOT NULL,
  asset_details STRING(255),
  asset_make STRING(20),
  asset_model STRING(20),
  asset_acquired_date TIMESTAMP,
  asset_disposed_date TIMESTAMP,
  other_asset_details STRING(255),
  FOREIGN KEY (maintenance_contract_id) REFERENCES Maintenance_Contracts(maintenance_contract_id),
  FOREIGN KEY (supplier_company_id) REFERENCES Third_Party_Companies(company_id)
) PRIMARY KEY (asset_id);

CREATE TABLE Asset_Parts (
  asset_id INT64 NOT NULL,
  part_id INT64 NOT NULL,
  FOREIGN KEY (part_id) REFERENCES Parts(part_id),
  FOREIGN KEY (asset_id) REFERENCES Assets(asset_id)
) PRIMARY KEY (asset_id, part_id);

CREATE TABLE Maintenance_Engineers (
  engineer_id INT64 NOT NULL GENERATED BY DEFAULT AS IDENTITY (START WITH 1 INCREMENT BY 1),
  company_id INT64 NOT NULL,
  first_name STRING(50),
  last_name STRING(50),
  other_details STRING(255),
  FOREIGN KEY (company_id) REFERENCES Third_Party_Companies(company_id)
) PRIMARY KEY (engineer_id);

CREATE TABLE Engineer_Skills (
  engineer_id INT64 NOT NULL,
  skill_id INT64 NOT NULL,
  FOREIGN KEY (engineer_id) REFERENCES Maintenance_Engineers(engineer_id),
  FOREIGN KEY (skill_id) REFERENCES Skills(skill_id)
) PRIMARY KEY (engineer_id, skill_id);

CREATE TABLE Fault_Log (
  fault_log_entry_id INT64 NOT NULL GENERATED BY DEFAULT AS IDENTITY (START WITH 1 INCREMENT BY 1),
  asset_id INT64 NOT NULL,
  recorded_by_staff_id INT64 NOT NULL,
  fault_log_entry_datetime TIMESTAMP,
  fault_description STRING(255),
  other_fault_details STRING(255),
  FOREIGN KEY (asset_id) REFERENCES Assets(asset_id),
  FOREIGN KEY (recorded_by_staff_id) REFERENCES Staff(staff_id)
) PRIMARY KEY (fault_log_entry_id);

CREATE TABLE Engineer_Visits (
  engineer_visit_id INT64 NOT NULL GENERATED BY DEFAULT AS IDENTITY (START WITH 1 INCREMENT BY 1),
  contact_staff_id INT64,
  engineer_id INT64 NOT NULL,
  fault_log_entry_id INT64 NOT NULL,
  fault_status STRING(10) NOT NULL,
  visit_start_datetime TIMESTAMP,
  visit_end_datetime TIMESTAMP,
  other_visit_details STRING(255),
  FOREIGN KEY (fault_log_entry_id) REFERENCES Fault_Log(fault_log_entry_id),
  FOREIGN KEY (engineer_id) REFERENCES Maintenance_Engineers(engineer_id),
  FOREIGN KEY (contact_staff_id) REFERENCES Staff(staff_id)
) PRIMARY KEY (engineer_visit_id);

CREATE TABLE Part_Faults (
  part_fault_id INT64 NOT NULL GENERATED BY DEFAULT AS IDENTITY (START WITH 1 INCREMENT BY 1),
  part_id INT64 NOT NULL,
  fault_short_name STRING(20),
  fault_description STRING(255),
  other_fault_details STRING(255),
  FOREIGN KEY (part_id) REFERENCES Parts(part_id)
) PRIMARY KEY (part_fault_id);

CREATE TABLE Fault_Log_Parts (
  fault_log_entry_id INT64 NOT NULL,
  part_fault_id INT64 NOT NULL,
  fault_status STRING(10) NOT NULL,
  FOREIGN KEY (part_fault_id) REFERENCES Part_Faults(part_fault_id),
  FOREIGN KEY (fault_log_entry_id) REFERENCES Fault_Log(fault_log_entry_id)
) PRIMARY KEY (fault_log_entry_id, part_fault_id);

CREATE TABLE Skills_Required_To_Fix (
  part_fault_id INT64 NOT NULL,
  skill_id INT64 NOT NULL,
  FOREIGN KEY (part_fault_id) REFERENCES Part_Faults(part_fault_id),
  FOREIGN KEY (skill_id) REFERENCES Skills(skill_id)
) PRIMARY KEY (part_fault_id, skill_id);